package com.application.intercom.utils

enum class PushKeys {
    address,
    visitorName,
    visitCategoryName,
    body,
    note,
    type,
    photo,
    title,
    flatName,
    mobileNumber,
    visitorId,
    CHECKED_IN,
    visitor_Id,
    New_Chat_Mesg,
    owner,
    reciverRole,
    New_Bill_Msg,
    NOTICE,
    NEW_COMPLAIN_RESOLVE,
    COMPLAIN_DENY,
    NEW_COMPLAIN,
    BUILDING_APPROVE,
    BUILDING_DENY,
    COMPLAIN_CONFIRM,
    VISITOR_ACCEPT_REJECT,
    REGULAR_CHECKED_IN,
    REGULAR_CHECKED_OUT,
    VISITOR_ADDED,
    GATEPASS_CREATE,
    BILL_APPROVED,
    NEW_RENT_Bill,
    reciverProfilePic,
    reciever,
    sender,
    roomId,
    senderRole,
    senderProfileName,
    senderProfilePic,
    senderPhoneNo,
    CHECKED_OUT,
    GATEPASS_COMPLETE,
    COMMENT_POST,
    LIKED_POST,
    POST,
    NEW_BUILDING,
    NEW_BILL_PAID,
    NEW_BILL_PAID_APPROVED,
    NEW_SERVICE_Bill,
    NEW_BILL_NOTIFY,
    New_Rent_Bill_Msg,
    BILL_REJECT


}