package com.application.intercom.utils

object SessionConstants {
    const val TOKEN = "token"
    const val ROLE = "role"
    const val SUBSCRIPTION = "subscription"
    const val KLONGITUDE = "logitude"
    const val KLATITUDE = "latitude"
    const val KADDRESS = "address"
    const val BUILDINGID = "buildingId"
    const val NAMEBUILDING = "name_building"
    const val NEWBUILDINGID = "newbuildingId"
    const val PROJECTID = "projectId"
    const val FLATID = "flatId"
    const val FLATNAME = "flat_name"
    const val USERID = "userId"
    const val PROFILEPIC = "profile_pic"
    const val OWNERNUMBER = "owner_number"
    const val USERDATAID = "user_data_id"
    const val COUNTRY = "country"
    const val NAME = "name"
    const val DEVICETOKEN = "device_token"
    const val AVAILABLE_CONTACTS = "availableContacts"
    const val TOTALS_CONTACTS = "totalContacts"
    const val DURATION = "duration"
    const val STOREID = "storeId"
    const val STORENAME = "storeName"
    const val LANG = "lang"
    const val MFSACCOUNT = "mfsaccount"
    const val MFSHOLDERNAME = "mfsholdername"
    const val MFS = "mfs"
    const val ACCOUNT = "account"
    const val HOLDERNAME = "holdername"
    const val ASSOCIATION_TYPE = "associationType"
    const val PAYTYPE = "paytype"
    const val MANAGERNAME = "managerName"
    const val NOTYTYPE = "noty_type"
    const val TITTLETYPE = "tittle_type"
    const val RECIEVER = "reciever"
    const val SENDER = "sender"
    const val RECIVERPROFILE = "reciverProfilePic"
    const val ROOMID = "roomId"
    const val SENDER_ROLE = "senderRole"
    const val SENDER_PROFILE_NAME = "senderProfileName"
    const val SENDER_PROFILE_PIC = "senderProfilePic"
    const val SENDER_PHONE_NO = "senderPhoneNo"


}